<?php 
@session_start();
define("PATHS","");//游戏目录
define("IP","localhost");//服务器IP
/*----------------------------------*/
define("DBIP","localhost");//数据库IP(一般不需修改)
define("DBUSERNAME","");//数据库用户名
define("DBPASSWORD","");//数据库密码
define("DBNAME","");//数据库表名
define("DBPORT","3306");//数据库端口
/*----------------------------------*/
define("SWAY",TRUE);//启动方式,TRUE为socket启动[推荐],FALSE为php原生函数启动
define("OSTYPE",TRUE);//面板运行环境,TRUE为Windows内核,FALSE为Linux内核
define("DEBUG",FALSE);//debug模式,TRUE为启用,FALSE为禁用,将会启用error_reporting函数
define("DDFS",FALSE);//是否启用删除数据函数,TRUE为启用,FALSE为禁用,[一旦删除,数据将无法恢复]
define("HNAME","URP");//导航栏名字
define("CSQL",FALSE);//是否启用创建数据库模块
define("SLINK","");//数据库后台页面(例:http://www.xxx.com/phpmyadmin/index.php)[若不启用CSQL则改函数可为空]
date_default_timezone_set("Asia/Shanghai");//定义时区,默认为中国上海时间
?>