<?php 
session_start();
define("PATHS","gamepath");//游戏目录
define("IP","localhost");//服务器IP
/*----------------------------------*/
define("DBIP","localhost");//数据库IP(一般不需修改)
define("DBUSERNAME","root");//数据库用户名
define("DBPASSWORD","root");//数据库密码
define("DBNAME","urp");//数据库表名
define("DBPORT","port");//数据库端口
/*----------------------------------*/
define("SWAY",TRUE);//启动方式,TRUE为socket启动[推荐],FALSE为php原生函数启动
define("DEBUG",FALSE);//debug模式,TRUE为启用,FALSE为禁用,将会启用error_reporting函数
define("DDFS",FALSE);//是否启用删除数据函数,TRUE为启用,FALSE为禁用,[一旦删除,数据将无法恢复]
define("HNAME","URP");//导航栏名字
date_default_timezone_set("Asia/Shanghai");//定义时区,默认为中国上海时间
?>